### ISSUE TITLE
Indigo Device Name in list of UniFi devices

### ISSUE THREAD

**Issue by autolog** [FlyingDiver/Indigo-miniUniFi#10]
If I select to add a UniFi device and sometime later go back and edit, then in the list of UniFi devices (using the names from the Controller), the top name in the list is the Indigo device name and the actula associated device is listed but not selected. Ideally, I think it should indicate the name of the UniFi device selected for the Indigo device? Doesn't seem to cause a problem though, albeit, it is slightly confusing as I wouldn't expect the Indigo device name to be listed.

**Comment by FlyingDiver** [comment]
Yeah, that's there because if the device is currently off-line, if you try to edit the device the pop up will be blank and the device won't be in the available devices list.  I'll see if I can change that to the last known name for that device.

**Comment by FlyingDiver** [comment]
Fixed in 0.0.11, I think.
