### ISSUE TITLE
State not updated in 0.0.10

### ISSUE THREAD

**Issue by autolog** [FlyingDiver/Indigo-miniUniFi#11]
UniFi devices setup before version 0.0.10 are showing a UI state of zero. New additions are now showing uptime. Not an issue to sort as I can just delete and redefine. Mentioning it in case it wasn't by design. :)

**Comment by FlyingDiver** [comment]
It's beta code. :)

Earlier releases had a sensor value field which is overriding the UI state I'm trying to set.  So yeah, it's intentional, more or less.
