### ISSUE TITLE
Version in Firmware Field?

### ISSUE THREAD

**Issue by autolog** [FlyingDiver/Indigo-miniUniFi#18]
A minor enhancement request to update the Indigo Firmware field in the UI from the UniFi Version state for UniFi devices..

Thanks for the ongoing updates. :)

**Comment by FlyingDiver** [comment]
Sounds reasonable.

**Comment by FlyingDiver** [comment]
Any idea how to set that field?  I can't find any reference to it.

**Comment by FlyingDiver** [comment]
Nevermind, I found it.  In next release.
