### ISSUE TITLE
Configure inactive devices

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-miniUniFi#2]
> Obviously you'll want to add a way to specify a Client that's not currently connected, either via MAC address or IP address.

Not sure what's the best way to do that without making the UI more complicated?  Different popup list?  Different section of the same list?

**Comment by jstewart99** [comment]
I don't know what's possible, but I would think at the bottom of the "active clients" popup list, an "Enter MAC address manually..." option would be cleanest.  Displaying "known clients" as opposed to "active clients" might be a better solution, though (or maybe just a checkbox in the Config section to specify what populates the popup list?).  I don't know if Unifi purges the known clients list after a period of time, but there's a risk that it could get unwieldy if you're in a more public wifi situation, so having that as the default might be a bad idea.  The need seems minimal/rare but HAVING to have a device online when you're setting things up is obviously a bit restrictive (the flip side is that the odds of knowing the MAC ID of a not-online/present device is probably low, so this is a fairly edge case situation that may not be worth solving).

**Comment by FlyingDiver** [comment]
Honestly, I'm not convinced this is worth trying to solve.  I don't think requiring the device to be on-line when setting it up is a huge burden.  If I get more feedback that it is, I'll make the inactive list accessible as well.  That list just tends to be much longer with a lot of old unused devices on it.  On my network, anyway.

**Comment by FlyingDiver** [comment]
Not worth the effort, IMO.  Subject to re-opening if a more compelling case is presented.
