### ISSUE TITLE
0.0.13 crash

### ISSUE THREAD

**Issue by Koreysherwin** [FlyingDiver/Indigo-miniUniFi#20]
Oct 28, 2020 at 5:55:31 PM
   Reloading plugin "miniUniFi 0.0.13"
   Stopping plugin "miniUniFi 0.0.13" (pid 345)
   Stopped plugin "miniUniFi 0.0.13"
   Starting plugin "miniUniFi 0.0.13" (pid 839)
   Started plugin "miniUniFi 0.0.13"
   miniUniFi                       Starting miniUniFi
   miniUniFi Debug                 updateFrequency = 60.0
   miniUniFi                       Barbie iPhone: Starting Device
   miniUniFi                       Korey iPhone: Starting Device
   miniUniFi                       Korey MBP 2016: Starting Device
   miniUniFi                       Sky Camera: Starting Device
   miniUniFi                       UDMP: Starting Device
   miniUniFi Debug                 Starting runConcurrentThread
   miniUniFi Debug                 UDMP: Updating controller
   miniUniFi Debug                 UDMP: Unifi OS controller detected
   miniUniFi Error                 Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 101, in runConcurrentThread
  File "plugin.py", line 271, in updateUniFiController
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/models.py", line 816, in json
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/simplejson/__init__.py", line 307, in loads
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/simplejson/decoder.py", line 335, in decode
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/simplejson/decoder.py", line 353, in raw_decode
ValueError: No JSON object could be decoded

   miniUniFi Error                 plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by FlyingDiver** [comment]
Turn on detailed debugging.  I need the line with "UniFi Controller Status Response: ".

**Comment by Koreysherwin** [comment]
`   Reloading plugin "miniUniFi 0.0.13"
   Stopping plugin "miniUniFi 0.0.13" (pid 839)
   miniUniFi                       Barbie iPhone: Stopping Device
   miniUniFi                       Korey iPhone: Stopping Device
   miniUniFi                       Korey MBP 2016: Stopping Device
   miniUniFi                       Sky Camera: Stopping Device
   miniUniFi                       UDMP: Stopping Device
   miniUniFi                       Shutting down miniUniFi
   Stopped plugin "miniUniFi 0.0.13"
   Starting plugin "miniUniFi 0.0.13" (pid 2153)
   Started plugin "miniUniFi 0.0.13"
   miniUniFi                       Starting miniUniFi
   miniUniFi Debug                 updateFrequency = 60.0
   miniUniFi                       Barbie iPhone: Starting Device
   miniUniFi                       Korey iPhone: Starting Device
   miniUniFi                       Korey MBP 2016: Starting Device
   miniUniFi                       Sky Camera: Starting Device
   miniUniFi                       UDMP: Starting Device
   miniUniFi Debug                 Starting runConcurrentThread
   miniUniFi Debug                 UDMP: Updating controller
   miniUniFi Debug                 UDMP: Unifi OS controller detected
   miniUniFi Threaddebug           UniFi Controller Login Response: {
  "unique_id": "ceb243e1-d6bb-4b4d-b391-f40f9eaa0117",
  "username": "test",
  "first_name": "Test",
  "last_name": "Er",
  "full_name": "Test Er",
  "email": "",
  "email_status": "UNVERIFIED",
  "phone": "",
  "avatar_relative_path": "",
  "status": "ACTIVE",
  "sso_account": "",
  "sso_uuid": "",
  "sso_username": "",
  "sso_picture": "",
  "create_time": 1603648968,
  "local_account_exist": true,
  "uid_sso_id": "",
  "uid_sso_account": "",
  "password_revision": 1603648968,
  "extras": {},
  "groups": [
    {
      "unique_id": "0df662cd-c9b2-4ea8-a21b-7c58aecfa265",
      "name": "616  UDM-Pro",
      "up_id": "",
      "up_ids": [],
      "system_name": "616  UDM-Pro",
      "create_time": "2020-09-03T13:36:40-07:00"
    }
  ],
  "roles": [
    {
      "unique_id": "30235a69-a024-4aff-a6bd-493b1f765e4d",
      "name": "Super Administrator",
      "system_role": true,
      "system_key": "super_administrator",
      "level": 2
    }
  ],
  "permissions": {
    "access.management": [
      "admin"
    ],
    "led.management": [
      "admin"
    ],
    "network.management": [
      "admin"
    ],
    "protect.management": [
      "admin"
    ],
    "system.management.location": [
      "admin"
    ],
    "system.management.user": [
      "admin"
    ],
    "talk.management": [
      "admin"
    ]
  },
  "scopes": [
    "write:protect.viewer",
    "write:protect.user:$",
    "write:protect.user",
    "write:protect.sensor",
    "write:protect.recordingSchedule",
    "write:protect.nvr",
    "write:protect.light",
    "write:protect.group",
    "write:protect.camera",
    "write:protect.bridge",
    "view:user_timezone",
    "view:user",
    "view:systemlog",
    "view:settings",
    "view:role",
    "view:permission:viewer",
    "view:permission:admin",
    "view:permission",
    "view:notification",
    "view:location_policy",
    "view:location_device",
    "view:location_activity",
    "view:location",
    "view:holiday_timezone",
    "view:holiday",
    "view:group",
    "view:door_group",
    "view:controller:talk",
    "view:controller:protect",
    "view:controller:network",
    "view:controller:led",
    "view:controller:access",
    "view:cloud_access",
    "view:app:users",
    "view:app:settings",
    "view:app:locations",
    "view:access.visitor",
    "view:access.systemlog",
    "view:access.settings",
    "view:access.schedule",
    "view:access.policy",
    "view:access.nfc_card",
    "view:access.face",
    "view:access.device",
    "view:access.dashboard",
    "update:access.device",
    "systemlog:user",
    "systemlog:system",
    "systemlog:location",
    "systemlog:access",
    "readmedia:protect.camera",
    "read:protect.viewer",
    "read:protect.user:$",
    "read:protect.user",
    "read:protect.sensor",
    "read:protect.recordingSchedule",
    "read:protect.nvr",
    "read:protect.light",
    "read:protect.group",
    "read:protect.camera",
    "read:protect.bridge",
    "notify:user",
    "notify:location",
    "notify:access",
    "manage:controller:talk",
    "manage:controller:network",
    "manage:controller:led",
    "manage:controller:access",
    "edit:user_timezone",
    "edit:user",
    "edit:systemlog",
    "edit:settings",
    "edit:role",
    "edit:permission:viewer",
    "edit:permission:admin",
    "edit:notification",
    "edit:location_policy",
    "edit:location_device",
    "edit:location_activity",
    "edit:location",
    "edit:holiday_timezone",
    "edit:holiday",
    "edit:group",
    "edit:feedback",
    "edit:door_group",
    "edit:access.visitor",
    "edit:access.settings",
    "edit:access.schedule",
    "edit:access.policy",
    "edit:access.nfc_card",
    "edit:access.face",
    "edit:access.device",
    "deletemedia:protect.camera",
    "delete:protect.viewer",
    "delete:protect.user:$",
    "delete:protect.user",
    "delete:protect.sensor",
    "delete:protect.recordingSchedule",
    "delete:protect.nvr",
    "delete:protect.light",
    "delete:protect.group",
    "delete:protect.camera",
    "delete:protect.bridge",
    "delete:access.device",
    "create:protect.viewer",
    "create:protect.user",
    "create:protect.sensor",
    "create:protect.recordingSchedule",
    "create:protect.liveview",
    "create:protect.light",
    "create:protect.group",
    "create:protect.camera",
    "create:protect.bridge",
    "assign:role",
    "adopt:access.device"
  ],
  "cloud_access_granted": false,
  "update_time": 1603833115,
  "avatar": "",
  "nfc_token": "",
  "nfc_display_id": "",
  "nfc_card_type": "",
  "nfc_card_status": "",
  "id": "ceb243e1-d6bb-4b4d-b391-f40f9eaa0117",
  "isOwner": false,
  "isSuperAdmin": true
}
   miniUniFi Threaddebug           UniFi Controller Status Response: 
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><link href="/2.css" rel="stylesheet"></head>
<body>
<div id="root"></div>
<script type="text/javascript" src="/vendor.3ea3704e.chunk.js"></script><script type="text/javascript" src="/main.c0fb843d.js"></script></body>
</html>

   miniUniFi Error                 Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 101, in runConcurrentThread
  File "plugin.py", line 271, in updateUniFiController
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/models.py", line 816, in json
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/simplejson/__init__.py", line 307, in loads
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/simplejson/decoder.py", line 335, in decode
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/simplejson/decoder.py", line 353, in raw_decode
ValueError: No JSON object could be decoded

   miniUniFi Error                 plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
`

**Comment by FlyingDiver** [comment]
OK, so the UDMP gives a LOT more info on the Login call, but doesn't understand the Status call.  I just pushed a commit, can you grab that one and try it?  I don't want to push a new release to try this out.

**Comment by FlyingDiver** [comment]
Or just change line 222 in plugin.py to:
`                status_url = "{}status"
`

**Comment by Koreysherwin** [comment]
standby

**Comment by Koreysherwin** [comment]
Changed line 222:

` 
   Starting plugin "miniUniFi 0.0.13" (pid 5120)
   Started plugin "miniUniFi 0.0.13"
   miniUniFi                       Starting miniUniFi
   miniUniFi Debug                 updateFrequency = 60.0
   miniUniFi                       Barbie iPhone: Starting Device
   miniUniFi                       Korey iPhone: Starting Device
   miniUniFi                       Korey MBP 2016: Starting Device
   miniUniFi                       Sky Camera: Starting Device
   miniUniFi                       UDMP: Starting Device
   miniUniFi Debug                 Starting runConcurrentThread
   miniUniFi Debug                 UDMP: Updating controller
   miniUniFi Debug                 UDMP: Unifi OS controller detected
   miniUniFi Threaddebug           UniFi Controller Login Response: {
  "unique_id": "ceb243e1-d6bb-4b4d-b391-f40f9eaa0117",
  "username": "test",
  "first_name": "Test",
  "last_name": "Er",
  "full_name": "Test Er",
  "email": "",
  "email_status": "UNVERIFIED",
  "phone": "",
  "avatar_relative_path": "",
  "status": "ACTIVE",
  "sso_account": "",
  "sso_uuid": "",
  "sso_username": "",
  "sso_picture": "",
  "create_time": 1603648968,
  "local_account_exist": true,
  "uid_sso_id": "",
  "uid_sso_account": "",
  "password_revision": 1603648968,
  "extras": {},
  "groups": [
    {
      "unique_id": "0df662cd-c9b2-4ea8-a21b-7c58aecfa265",
      "name": "616  UDM-Pro",
      "up_id": "",
      "up_ids": [],
      "system_name": "616  UDM-Pro",
      "create_time": "2020-09-03T13:36:40-07:00"
    }
  ],
  "roles": [
    {
      "unique_id": "30235a69-a024-4aff-a6bd-493b1f765e4d",
      "name": "Super Administrator",
      "system_role": true,
      "system_key": "super_administrator",
      "level": 2
    }
  ],
  "permissions": {
    "access.management": [
      "admin"
    ],
    "led.management": [
      "admin"
    ],
    "network.management": [
      "admin"
    ],
    "protect.management": [
      "admin"
    ],
    "system.management.location": [
      "admin"
    ],
    "system.management.user": [
      "admin"
    ],
    "talk.management": [
      "admin"
    ]
  },
  "scopes": [
    "write:protect.viewer",
    "write:protect.user:$",
    "write:protect.user",
    "write:protect.sensor",
    "write:protect.recordingSchedule",
    "write:protect.nvr",
    "write:protect.light",
    "write:protect.group",
    "write:protect.camera",
    "write:protect.bridge",
    "view:user_timezone",
    "view:user",
    "view:systemlog",
    "view:settings",
    "view:role",
    "view:permission:viewer",
    "view:permission:admin",
    "view:permission",
    "view:notification",
    "view:location_policy",
    "view:location_device",
    "view:location_activity",
    "view:location",
    "view:holiday_timezone",
    "view:holiday",
    "view:group",
    "view:door_group",
    "view:controller:talk",
    "view:controller:protect",
    "view:controller:network",
    "view:controller:led",
    "view:controller:access",
    "view:cloud_access",
    "view:app:users",
    "view:app:settings",
    "view:app:locations",
    "view:access.visitor",
    "view:access.systemlog",
    "view:access.settings",
    "view:access.schedule",
    "view:access.policy",
    "view:access.nfc_card",
    "view:access.face",
    "view:access.device",
    "view:access.dashboard",
    "update:access.device",
    "systemlog:user",
    "systemlog:system",
    "systemlog:location",
    "systemlog:access",
    "readmedia:protect.camera",
    "read:protect.viewer",
    "read:protect.user:$",
    "read:protect.user",
    "read:protect.sensor",
    "read:protect.recordingSchedule",
    "read:protect.nvr",
    "read:protect.light",
    "read:protect.group",
    "read:protect.camera",
    "read:protect.bridge",
    "notify:user",
    "notify:location",
    "notify:access",
    "manage:controller:talk",
    "manage:controller:network",
    "manage:controller:led",
    "manage:controller:access",
    "edit:user_timezone",
    "edit:user",
    "edit:systemlog",
    "edit:settings",
    "edit:role",
    "edit:permission:viewer",
    "edit:permission:admin",
    "edit:notification",
    "edit:location_policy",
    "edit:location_device",
    "edit:location_activity",
    "edit:location",
    "edit:holiday_timezone",
    "edit:holiday",
    "edit:group",
    "edit:feedback",
    "edit:door_group",
    "edit:access.visitor",
    "edit:access.settings",
    "edit:access.schedule",
    "edit:access.policy",
    "edit:access.nfc_card",
    "edit:access.face",
    "edit:access.device",
    "deletemedia:protect.camera",
    "delete:protect.viewer",
    "delete:protect.user:$",
    "delete:protect.user",
    "delete:protect.sensor",
    "delete:protect.recordingSchedule",
    "delete:protect.nvr",
    "delete:protect.light",
    "delete:protect.group",
    "delete:protect.camera",
    "delete:protect.bridge",
    "delete:access.device",
    "create:protect.viewer",
    "create:protect.user",
    "create:protect.sensor",
    "create:protect.recordingSchedule",
    "create:protect.liveview",
    "create:protect.light",
    "create:protect.group",
    "create:protect.camera",
    "create:protect.bridge",
    "assign:role",
    "adopt:access.device"
  ],
  "cloud_access_granted": false,
  "update_time": 1603833115,
  "avatar": "",
  "nfc_token": "",
  "nfc_display_id": "",
  "nfc_card_type": "",
  "nfc_card_status": "",
  "id": "ceb243e1-d6bb-4b4d-b391-f40f9eaa0117",
  "isOwner": false,
  "isSuperAdmin": true
}
   miniUniFi Threaddebug           UniFi Controller Status Response: 
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><link href="/2.css" rel="stylesheet"></head>
<body>
<div id="root"></div>
<script type="text/javascript" src="/vendor.3ea3704e.chunk.js"></script><script type="text/javascript" src="/main.c0fb843d.js"></script></body>
</html>

   miniUniFi Error                 Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 101, in runConcurrentThread
  File "plugin.py", line 271, in updateUniFiController
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/models.py", line 816, in json
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/simplejson/__init__.py", line 307, in loads
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/simplejson/decoder.py", line 335, in decode
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/simplejson/decoder.py", line 353, in raw_decode
ValueError: No JSON object could be decoded

   miniUniFi Error                 plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
`

**Comment by FlyingDiver** [comment]
OK, so it doesn't like that URL either.  Hmmm.  The docs I have are really ambiguous about this one.  See if either of these work:

`                status_url = "{}proxy/network/status"`
`                status_url = "{}proxy/network/api/status"`

**Comment by FlyingDiver** [comment]
I don't need all the output, just the lines after "UniFi Controller Status Response: "

**Comment by Koreysherwin** [comment]
status_url = "{}proxy/network/status"

works, no error

`   miniUniFi Threaddebug           UniFi Controller Status Response: {"meta":{"rc":"ok","uuid":"177f8879-29bb-5f58-ae2e-3eb1cf8ab5bd","server_version":"5.14.24","server_running":true,"db_running":true,"db_connected":true,"db_journaling":false,"db_repairing":false,"db_importing":false,"db_importing_at":-1,"db_importing_name":null,"ucore_installation":true,"udm_connected":true},"data":[]}
   miniUniFi Debug                 UDMP: UniFi Controller Getting Sites
   miniUniFi Threaddebug           didDeviceCommPropertyChange: UDMP -> UDMP
   miniUniFi Threaddebug           origDev:\address : 192.168.0.254
batteryLevel : None
buttonGroupCount : 0
configured : True
description : 
deviceTypeId : unifiController
displayStateId : status
displayStateImageSel : SensorOn
displayStateValRaw : Login OK
displayStateValUi : Login OK
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 1501775312
globalProps : MetaProps : (dict)
     com.flyingdiver.indigoplugin.miniUniFi : (dict)
          address : 192.168.0.254 (string)
          controllerType : UDMPro (string)
          password : Tester1 (string)
          port : 443 (string)
          ssl_verify : false (bool)
          username : test (string)
id : 55391458
lastChanged : 2020-10-28 18:26:58
lastSuccessfulComm : 2020-10-28 18:26:58
model : UniFi Controller
name : UDMP
ownerProps : com.flyingdiver.indigoplugin.miniUniFi : (dict)
     address : 192.168.0.254 (string)
     controllerType : UDMPro (string)
     password : Tester1 (string)
     port : 443 (string)
     ssl_verify : false (bool)
     username : test (string)
pluginId : com.flyingdiver.indigoplugin.miniUniFi
pluginProps : com.flyingdiver.indigoplugin.miniUniFi : (dict)
     address : 192.168.0.254 (string)
     controllerType : UDMPro (string)
--snip--
`

**Comment by FlyingDiver** [comment]
Try 0.0.14.

**Comment by Koreysherwin** [comment]
works!

`
Oct 28, 2020 at 6:35:09 PM
   Reloading plugin "miniUniFi 0.0.14"
   Stopping plugin "miniUniFi 0.0.14" (pid 8564)
   Stopped plugin "miniUniFi 0.0.14"
   Starting plugin "miniUniFi 0.0.14" (pid 8647)
   Started plugin "miniUniFi 0.0.14"
   miniUniFi                       Starting miniUniFi
   miniUniFi Debug                 updateFrequency = 60.0
   miniUniFi                       Ap - Patio: Starting Device
   miniUniFi                       Barbie iPhone: Starting Device
   miniUniFi                       Korey iPhone: Starting Device
   miniUniFi                       Korey MBP 2016: Starting Device
   miniUniFi                       Sky Camera: Starting Device
   miniUniFi                       UDMP: Starting Device
   miniUniFi Debug                 Starting runConcurrentThread
   miniUniFi Debug                 UDMP: Updating controller
   miniUniFi Debug                 UDMP: Unifi OS controller detected
   miniUniFi Debug                 UDMP: UniFi Controller Getting Sites
   miniUniFi Debug                 Korey MBP 2016: Online @ KnB
   miniUniFi Debug                 Sky Camera: Online
   miniUniFi Debug                 Korey iPhone: Online @ KnB
   miniUniFi Debug                 Barbie iPhone: Online @ KnB
   miniUniFi Debug                 Ap - Patio: Online`

**Comment by FlyingDiver** [comment]
Is the SW version showing in the "Firmware" column of the Indigo client.

**Comment by Koreysherwin** [comment]
Not seeing a Firmware State?
<img width="341" alt="Screen Shot 2020-10-28 at 6 45 05 PM" src="https://user-images.githubusercontent.com/51178437/97515190-c8fafc00-194d-11eb-9414-453b8c964823.png">

**Comment by FlyingDiver** [comment]
Not the state list:
<img width="785" alt="Screen Shot 2020-10-28 at 9 49 11 PM" src="https://user-images.githubusercontent.com/72976/97515461-72022080-1967-11eb-8309-1f48e72406b1.png">

**Comment by FlyingDiver** [comment]
You might need to add that column to the UI.  Right click anywhere in that bar.

**Comment by Koreysherwin** [comment]
it's there:


no firmware showing for the G3 IP camera:

<img width="1233" alt="Screen Shot 2020-10-28 at 6 59 24 PM" src="https://user-images.githubusercontent.com/51178437/97516140-b7b2ef00-194f-11eb-9b77-87c8e1107720.png">

**Comment by FlyingDiver** [comment]
Looks like the controller reports the camera as a client, not a UniFI device, if I'm reading the model column correctly.  I don't even look at version info for clients.

What's in the type and model states for the UDMP 616 device?

**Comment by Koreysherwin** [comment]
Model = UDMPRO
TYPE = udm
<img width="365" alt="Screen Shot 2020-10-28 at 7 37 13 PM" src="https://user-images.githubusercontent.com/51178437/97518751-20509a80-1955-11eb-9ccd-22e4d10cbf0e.png">
<img width="348" alt="Screen Shot 2020-10-28 at 7 37 32 PM" src="https://user-images.githubusercontent.com/51178437/97518766-25ade500-1955-11eb-8e36-76ad85824816.png">

**Comment by FlyingDiver** [comment]
Great.  I'll put that model info in the next release.

**Comment by Koreysherwin** [comment]
No camera show up, nor does the 48 port switch

<img width="535" alt="Screen Shot 2020-10-28 at 7 39 41 PM" src="https://user-images.githubusercontent.com/51178437/97518872-5e4dbe80-1955-11eb-9c94-b41b834d1816.png">

**Comment by FlyingDiver** [comment]
Where do they show up in the UniFI web UI?  Under devices or clients?

**Comment by FlyingDiver** [comment]
What kind of switch?

**Comment by Koreysherwin** [comment]
in the controller under devices:

<img width="1299" alt="Screen Shot 2020-10-28 at 7 50 48 PM" src="https://user-images.githubusercontent.com/51178437/97519720-ea141a80-1956-11eb-92f6-65fa14219282.png">

**Comment by Koreysherwin** [comment]
UniFi Switch 48 AT-500W

**Comment by FlyingDiver** [comment]
Weird.  And where did that "--none--" come from?  I'm not adding it to the list.

<img width="518" alt="Screen Shot 2020-10-28 at 10 53 07 PM" src="https://user-images.githubusercontent.com/72976/97519905-7252e980-1970-11eb-8a2c-a7e6499e663a.png">

**Comment by Koreysherwin** [comment]
you got me.. perhaps that's the switch, let me add that and see what it does

**Comment by Koreysherwin** [comment]
Yes, that's the switch.

<img width="356" alt="Screen Shot 2020-10-28 at 7 55 27 PM" src="https://user-images.githubusercontent.com/51178437/97520020-8ccc9900-1957-11eb-9985-c357fa28551d.png">

**Comment by FlyingDiver** [comment]
Oh, wait, that's what I'm putting in the list when no 'name' or 'hostname' in the states.  Is there any state with the name in it.

**Comment by Koreysherwin** [comment]
model: S248500

<img width="1303" alt="Screen Shot 2020-10-28 at 7 57 43 PM" src="https://user-images.githubusercontent.com/51178437/97520192-dcab6000-1957-11eb-9643-06eb5ecdbd81.png">

**Comment by FlyingDiver** [comment]
Maybe you never gave it a name in the web UI.  I guess I could fall back to the 'model' state.

**Comment by Koreysherwin** [comment]
yes that was the deal, no Alias in the controller, added one now it shows.
<img width="550" alt="Screen Shot 2020-10-28 at 8 01 29 PM" src="https://user-images.githubusercontent.com/51178437/97520437-7a9f2a80-1958-11eb-956f-51f9fe755398.png">

**Comment by FlyingDiver** [comment]
OK, I'm now checking for 'name', then 'hostname', then 'model' before I punt on the name.  ;)

**Comment by Koreysherwin** [comment]
interesting now too, since I added the G3 camera as a client it now shows in devices, but offline:
<img width="562" alt="Screen Shot 2020-10-28 at 8 00 12 PM" src="https://user-images.githubusercontent.com/51178437/97520497-9c98ad00-1958-11eb-9a6f-f67a70f59832.png">

**Comment by FlyingDiver** [comment]
They both had the same "name" before, which was messing up the list, I think.  
Devices should show up on or offline.  Anything that's adopted by the controller.

**Comment by Koreysherwin** [comment]
that one is my weather camera BTW: 😁

https://admin.meteobridge.com/cam/8d0ff1a8bad9e8e915751f42ee099abc/camplus.jpg

**Comment by FlyingDiver** [comment]
Time to crash.  If you see anything else, let me know and I'll deal with it tomorrow.

**Comment by Koreysherwin** [comment]
Deleted it and now it does not show the camera in devices list:

Good night.


<img width="559" alt="Screen Shot 2020-10-28 at 8 06 23 PM" src="https://user-images.githubusercontent.com/51178437/97520745-2183c680-1959-11eb-9443-d9e2fb49c54f.png">

**Comment by FlyingDiver** [comment]
I was doing the name fixes wrong (wrong place in the code).  Fixing it now.

**Comment by FlyingDiver** [comment]
Should be finally fixed in 0.0.15.
