### ISSUE TITLE
0.0.14 Loading error

### ISSUE THREAD

**Issue by Highsteads** [FlyingDiver/Indigo-miniUniFi#22]
29 Oct 2020 at 09:33:13
   Enabling plugin "miniUniFi 0.0.14"
   Starting plugin "miniUniFi 0.0.14" (pid 32981)
   Started plugin "miniUniFi 0.0.14"
   miniUniFi                       Starting miniUniFi
   miniUniFi Debug                 updateFrequency = 30.0
   miniUniFi                       Apple Watch 5: Starting Device
   miniUniFi                       Apple Watch 6: Starting Device
   miniUniFi                       iPhone 11 Pro Max: Starting Device
   miniUniFi                       iPhone 7+: Starting Device
   miniUniFi                       UniFi Controller: Starting Device
   miniUniFi Debug                 Starting runConcurrentThread
   miniUniFi Debug                 UniFi Controller: Updating controller
   miniUniFi Debug                 UniFi Controller: Unifi Standard controller detected
   miniUniFi Threaddebug           UniFi Controller Login Response: {"meta":{"rc":"ok"},"data":[]}
   miniUniFi Threaddebug           UniFi Controller Status Response: {"meta":{"rc":"ok","up":true,"server_version":"5.12.66","uuid":"8b1669aa-0803-565b-adb1-bff4df50c582"},"data":[]}
   miniUniFi Error                 Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 101, in runConcurrentThread
  File "plugin.py", line 277, in updateUniFiController
KeyError: 'key version not found in dict'

   miniUniFi Error                 plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   Disabling plugin "miniUniFi 0.0.14"
   Stopping plugin "miniUniFi 0.0.14" (pid 32981)
   miniUniFi                       Apple Watch 5: Stopping Device
   miniUniFi                       Apple Watch 6: Stopping Device
   miniUniFi                       iPhone 11 Pro Max: Stopping Device
   miniUniFi                       iPhone 7+: Stopping Device
   miniUniFi                       UniFi Controller: Stopping Device
   miniUniFi                       Shutting down miniUniFi
   Stopped plugin "miniUniFi 0.0.14"

**Comment by FlyingDiver** [comment]
Thanks!

**Comment by FlyingDiver** [comment]
Fixed in 0.0.15
