### ISSUE TITLE
Feature request: UniFi Protect camera motion detection

### ISSUE THREAD

**Issue by madpsintst** [FlyingDiver/Indigo-miniUniFi#26]
Thanks for the great plug-in. I am using it for geofencing; more specifically, I use it to detect the presence of cell phones on the wireless network to determine who is home. When nobody is home, the house goes into energy saving mode.

Just thought I would add a feature request. It would be great if a device representing UniFi Protect video cameras and Protect doorbells could be setup, and then indicate whether motion has occurred or the doorbell button has been pressed.

Thanks!

**Comment by FlyingDiver** [comment]
I'll need a copy of the controller data for those device.  In the plugin menu, there's a item "write controller data to log".  Please run that, then copy the output to a text file, zip it up, and attach it to this issue.  It's going to be really long, so don't try to paste it directly into a comment.

**Comment by FlyingDiver** [comment]
Also, I'm not sure motion or bell press is going to work, since I can only poll the controller for the data.  No pushes from the controller.  So unless there's something in the device data saying that an event has happened recently, it's not likely to tell you anything useful.

**Comment by madpsintst** [comment]
Thanks. I have the log file ready but would rather not post it publicly. Is there a way for me to send it to you privately? 

The UniFi Doorbell does include the ability to push notifications to my phone upon motion detection. Not sure if this means it's pushing a signal to the controller.

**Comment by FlyingDiver** [comment]
I think you can PM it to me on the Indigo website.

**Comment by madpsintst** [comment]
Done! Thanks.

**Comment by FlyingDiver** [comment]
I just don't see anything obvious in the data that shows a recent event for either device type.  If you can find a reference anywhere that someone else (other than Ubiquiti) has done this, let me know.
