### ISSUE TITLE
Plugin creation date

### ISSUE THREAD

**Issue by jstewart99** [FlyingDiver/Indigo-miniUniFi#27]
Plug-in file creation date is (and has been) sometime in 2017, would be helpful for version tracking/comparison if the creation date was correct

**Comment by FlyingDiver** [comment]
It is correct.  That's the date the .indigoPlugin wrapper was created (it was copied from an older plugin).  Even if I changed it now, it wouldn't ever update again as I change the contents.  That's just the way it works in MacOS.

**Comment by FlyingDiver** [comment]
Why would you be comparing different versions of the plugin wrapper?

**Comment by jstewart99** [comment]
It's just odd when I download the plug-in that it goes to the bottom of the Downloads folder as I have it sorted by Modification Date even though it's a new release.  Just causes a bit of confusion if it's "the new version that I just downloaded" or some leftover older version.  It appears that other plug-ins' creation date mimics their release date, but if "that's just the way it works" then it's obviously not a major deal, just wasn't sure if it was an error or not.

**Comment by FlyingDiver** [comment]
There were some weird permissions on that folder.  I've cleared them and updated the timestamp on the wrapper.  We'll see if it behaves in the future.
