### ISSUE TITLE
Add display state for elapsed time

### ISSUE THREAD

**Issue by cronutan** [FlyingDiver/Indigo-miniUniFi#28]
Currently I use the uptime and offline_seconds to show on controll pages, but I can't use these values directly so I setup variables and triggers to convert them.  It would be very convenient to have them in some user readable state like  1 day, 4 hours, 34 min

**Comment by FlyingDiver** [comment]
Uptime is already available as the device state in a readable format.  You can select it from the device configuration dialog.

**Comment by cronutan** [comment]
Which device configuration dialog.  I don't see it.
![Screen Shot 2021-03-28 at 5 33 38 PM](https://user-images.githubusercontent.com/78983204/112768801-c9c2b780-8feb-11eb-86e2-8541484eb4fa.png)
![Screen Shot 2021-03-28 at 5 35 24 PM](https://user-images.githubusercontent.com/78983204/112768853-055d8180-8fec-11eb-98f3-685cba80cb80.png)

**Comment by FlyingDiver** [comment]
My mistake, it's shown as the UI value in the Indigo client, but that's not actually available for display on a control page.  I thought it was.

**Comment by cronutan** [comment]
Ok. Is it something you would be interested in adding?  If not, I'll try the device extensions plugin you suggested?

**Comment by FlyingDiver** [comment]
Try device extensions.

**Comment by cronutan** [comment]
There is "convert date time format" and "convert date/time to elapsed minutes".  Fiddling with them, I don't see how I could change seconds to days, hours, minutes.  Converting time formats would not accept seconds (%S) and returned nothing for %d %H:%M:%S

**Comment by FlyingDiver** [comment]
I've never actually used that plugin, I just remembered it did time conversions.
