### ISSUE TITLE
KeyError: radio_table_stats

### ISSUE THREAD

**Issue by howartp84** [FlyingDiver/Indigo-miniUniFi#29]
Hi Joe

Just swapped from Karls' plugin to yours.

Controller device working fine.

Added AP device showing "Wifi Info" and I get log full of:

> 2021-04-03 15:22:20.274	miniUniFi Error	plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
> 2021-04-03 15:23:20.633	miniUniFi Error	Error in plugin execution runConcurrentThread:
> 
> Traceback (most recent call last):
>   File "plugin.py", line 122, in runConcurrentThread
>   File "plugin.py", line 485, in updateUniFiDevice
> KeyError: 'radio_table_stats'
>

**Comment by FlyingDiver** [comment]
What model of WAP?  

Use the menu command to write the controller data to the log.  Then copy and paste it to a text file and attach it here.
<img width="496" alt="Screen Shot 2021-04-03 at 10 28 14 AM" src="https://user-images.githubusercontent.com/72976/113481403-66131100-9467-11eb-9db3-8884dfb5554b.png">

**Comment by howartp84** [comment]
[UniFiLog.txt](https://github.com/FlyingDiver/Indigo-miniUniFi/files/6252711/UniFiLog.txt)
It's the bog standard "UniFi AP" in the controller ui.

**Comment by FlyingDiver** [comment]
`                "version": "3.7.58.6385",`

That's a pretty old firmware version.  Mine are all running 4.3.28.X.  Any chance that could be upgraded?  I think they changed the data format.

**Comment by FlyingDiver** [comment]
Also, you have the Unifi software running (somewhere) and one AP, that's it?

**Comment by howartp84** [comment]
I can do; at work I keep them on stable because there's so many unstable versions of UniFi firmware!

I'll see what i'm running at church; this is one AP of a three pack I bought for Church and 'borrowed'.

**Comment by FlyingDiver** [comment]
I'm trying to eliminate variables.  I don't know if the lack of that specific dict in the data is because of the AP model or the firmware.  I've already dealt with the issue that some APs have one radio and some have two.

**Comment by howartp84** [comment]
Thanks that's sorted it - though the controller now telling me the AP is EOL and I can't upgrade make any changes to the config of the AP now.  Grrr!

**Comment by FlyingDiver** [comment]
On of mine is EOL as well,  And it's the hardest one to get to (12' ceiling in a closet).
