### ISSUE TITLE
Log issue

### ISSUE THREAD

**Issue by Koreysherwin** [FlyingDiver/Indigo-miniUniFi#30]
Seems the plugin is writing huge log files.

I have only critical errors set to show in the event log.
<img width="607" alt="Screen Shot 2021-04-16 at 10 08 17 PM" src="https://user-images.githubusercontent.com/51178437/115102523-41f00f00-9f00-11eb-8661-0bb903b4db77.png">

V0.1.2

<img width="432" alt="Screen Shot 2021-04-16 at 10 03 56 PM" src="https://user-images.githubusercontent.com/51178437/115102491-05bcae80-9f00-11eb-8f3e-68f485a90bc9.png">

**Comment by FlyingDiver** [comment]
I need to figure out how to set the log level for the plugin specific log in addition to the main indigo log.

**Comment by FlyingDiver** [comment]
Is this still happening?  I'm not seeing it on my system.

**Comment by FlyingDiver** [comment]
Might be fixed in 2022.0.1.

**Comment by FlyingDiver** [comment]
Fixed.  Plugin log matches the log level of the Indigo log.

**Comment by Koreysherwin** [comment]
I had quit using it due to the log file issues i was having, installed the new version this morning and so far so good!!

—
Korey Sherwin
SherwinSound.com
702-239-1195
