### ISSUE TITLE
About menu.

### ISSUE THREAD

**Issue by Koreysherwin** [FlyingDiver/Indigo-miniUniFi#31]
<img width="267" alt="Screen Shot 2021-04-16 at 10 28 50 PM" src="https://user-images.githubusercontent.com/51178437/115102963-220e1a80-9f03-11eb-8002-71fd282c2b88.png">
v0.1.2.

takes you to MyQ

https://forums.indigodomo.com/viewforum.php?f=214

**Comment by FlyingDiver** [comment]
Fixed it next release.  Now points to GitHub.
