### ISSUE TITLE
Updating device to Access Point fails with AC-Lites

### ISSUE THREAD

**Issue by jstewart99** [FlyingDiver/Indigo-miniUniFi#32]
Tried to change some old "Unifi Device" APs to the updated "Access Point".  A few worked fine, but I noticed the two AC-Lite's that I have did not update and started throwing errors in the Log.  I'd suspect the older UAP-LR might also run into a similar problem (I'd already updated it a while ago through so I'm not sure).  AC-Pro and AC-LR updated fine.  Log error for the Lites:

Traceback (most recent call last):
  File "plugin.py", line 122, in runConcurrentThread
KeyError: 'key id 786171553 not found in database'

I can delete and recreate I'm sure, it's just a hassle since I have some Control Page stuff set up that requires retooling if I go that route, so the ability to update the device type would be handy.

**Comment by FlyingDiver** [comment]
I have one UAP-Pro, 2 x UAP-AC-Pro, and one UAP-AC-M.  Those all work.  I don't know if anyone ever tried an AC-Lite before.

Can you run the "Write Controller Data to Log" menu command, then put that in a zipped plain text file and attach it to this issue?

**Comment by jstewart99** [comment]
Data file attached as requested.  The two devices were still set to "Access Point" but weren't updating (they still showed Uptime rather than Wifi info as I'd selected).  I changed them back to the old "Unifi Device", saved that, then set them back to Access Point, which should be reflected in the log.

The 786.. device ID doesn't appear to be any current device, which is interesting. That error may be unrelated to the inability to update the device type of the AC-Lites.   I did have two AP's that were basically duplicated (i.e. I think one was the original "Unifi Device" type that was the only option in the first few versions of the plug-in, and and the other was the newer "Access Point" type that I'd created as a test a few versions ago but never integrated into my Control Page.  Today I updated to the newest plugin version, and after changing the OLDER Unifi Device types to Access Points, I deleted the previous Access Point ones that I'd created a few versions ago.  So maybe that process broke something. I probably just ran into a "nobody else will ever run into this bug" situation and just need to delete and recreate, but let me know what you'd like me to do.  Again this may or may not be related to the fact that I can't update the AC-Lites like I could the other AP's.

[ControllerData.zip](https://github.com/FlyingDiver/Indigo-miniUniFi/files/6804283/ControllerData.zip)

**Comment by FlyingDiver** [comment]
Unless you're in a huge hurry, give me a few days to dig into that data.

**Comment by jstewart99** [comment]
Zero rush, and you owe me nothing for this fine free plugin so take your time sir! :)

**Comment by jstewart99** [comment]
Hold up, just reloaded the plugin and everything seems to have resolved.  I swear I thought I'd already done that but I guess not.  Ugh...sorry for the time waste (aside from the "About" menu item going to the wrong forum page, haha).  Deleting my data file post for privacy reasons.

**Comment by jstewart99** [comment]
One other unrelated thing, I just noticed my MiniUnifi plugin Log folder is like 14GB (has the last 5 days at nearly 3GB each file.  Is that normal?  Bit of a disk space hog.  I'm pretty sure I just had the logging set to Warning Messages (not sure if that's related as to what writes to the main Log file).

**Comment by FlyingDiver** [comment]
Yeah, you can delete that.  I probably put too much in there.
