### ISSUE TITLE
Client list empty

### ISSUE THREAD

**Issue by compwiz777** [FlyingDiver/Indigo-miniUniFi#34]
Added controller and it shows logged in successful, but when I go to add a client both wired and wireless client list is empty and I get the error below showing in logs:

   miniUniFi Error                 Error in plugin execution GetUiDynamicList:

  File "plugin.py", line 594, in get_client_list
type: 'dict' object has no attribute 'iteritems'

**Comment by FlyingDiver** [comment]
Fixed in 2022.0.1
