### ISSUE TITLE
Switch POE Power Cycle Feature Request

### ISSUE THREAD

**Issue by autolog** [FlyingDiver/Indigo-miniUniFi#35]
It would be useful to have an Indigo Action to be able to power cycle a POE port on a switch. Use case, is the requirement I have to pwer cycle a POE attached camera that becomes uncommunicative.

**Comment by FlyingDiver** [comment]
Working for standard controllers.  Not working for Unifi OS controllers.

**Comment by FlyingDiver** [comment]
Now working in 2022.1.1
