### ISSUE TITLE
Dictionary changed size during iteration

### ISSUE THREAD

**Issue by autolog** [FlyingDiver/Indigo-miniUniFi#38]
Running latest pre-relaese code from repository as advised last night.

Added a new UniFi device (UXG-Pro) to miniUnifi and got this error:
`   miniUniFi Error                 Error in plugin execution runConcurrentThread:

  File "plugin.py", line 113, in runConcurrentThread
type: dictionary changed size during iteration

   miniUniFi Error                 plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
`
I guess beacuse the device was added to the dictionary while the iteration was in progress?

**Comment by FlyingDiver** [comment]
Yeah, that's a Python3 change I'm not thrilled with.

**Comment by FlyingDiver** [comment]
https://github.com/FlyingDiver/Indigo-miniUniFi/releases/tag/2022.1.2
