### ISSUE TITLE
UDMP Authentication failure

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-miniUniFi#9]
Testing on UDMP running 1.8.1-rc3
```
Started plugin "miniUniFi 0.0.3"
   miniUniFi Error                 Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 85, in runConcurrentThread
  File "plugin.py", line 186, in updateUniFiController
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 520, in post
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='192.168.0.254', port=8443): Max retries exceeded with url: /proxy/network/api/auth/login (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10ac92fd0>: Failed to establish a new connection: [Errno 61] Connection refused',))

   miniUniFi Error                 plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
```

**Comment by FlyingDiver** [comment]
That IP address seems very suspect. The UDMP is actually on .254?

**Comment by DoctorQ991** [comment]
My IP is 10.0.1.1 and I get the same error. UDMP running 1.8.0 FW, controller 5.14.22 build 13865.

**Comment by FlyingDiver** [comment]
What's the URL you end up at when connecting to the web interface?

**Comment by DoctorQ991** [comment]
https://10.0.1.1/network/site/default/dashboard

**Comment by Koreysherwin** [comment]
Yes that is the correct IP.


<img width="797" alt="Screen Shot 2020-10-24 at 6 30 14 PM" src="https://user-images.githubusercontent.com/51178437/97096863-0cd8c300-1627-11eb-888e-5f9c2af90b4f.png">

**Comment by FlyingDiver** [comment]
OK, I'm researching the difference in the API URLs for the UDMP.  I thought I had the right code based on my original source, but I'm looking at more now.  This is all undocumented API, so it's a little tricky.

**Comment by Koreysherwin** [comment]
if you need access to the unit, let me know I can setup an account for you.

I had Karl snooping around for awhile. 😆

**Comment by FlyingDiver** [comment]
Both of you are getting the exact same error?  

Do me a favor and pick the non-Pro controller type and see what errors you get.

**Comment by DoctorQ991** [comment]
Last line of error is slightly different

Traceback (most recent call last):
  File "plugin.py", line 85, in runConcurrentThread
  File "plugin.py", line 186, in updateUniFiController
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 520, in post
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='10.0.1.1', port=8443): Max retries exceeded with url: /api/login (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x105cdd590>: Failed to establish a new connection: [Errno 61] Connection refused',))

   miniUniFi Error                 plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by FlyingDiver** [comment]
Honestly, this is looking like a firewall or similar error.  Connection refused means it's not even getting the connection to make the HTTP request.

Does the UDMP have a configuration section where you can specify which IP addresses or networks can connect?

**Comment by DoctorQ991** [comment]
That was for the UDM. This is for SW:

Traceback (most recent call last):
  File "plugin.py", line 85, in runConcurrentThread
  File "plugin.py", line 186, in updateUniFiController
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 520, in post
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='10.0.1.1', port=8443): Max retries exceeded with url: /api/login (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x105cdd290>: Failed to establish a new connection: [Errno 61] Connection refused',))

   miniUniFi Error                 plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by FlyingDiver** [comment]
Yeah, so same error.  Before it even processed the HTTP request.  Something is blocking the connection.

**Comment by DoctorQ991** [comment]
I just tried opening all local IPs to the UDMPs MAC address in the firewall, something that seems redundant, no joy. I've been unable to access Security Spy outside of the LAN since I installed the UDMP, so I'm still fumbling around with learning Ubiquiti's software.

**Comment by FlyingDiver** [comment]
It might be worth installing this software and seeing if it can connect to the UDMP.

https://github.com/Art-of-WiFi/UniFi-API-client

**Comment by DoctorQ991** [comment]
Er, you must have mistaken me for a programmer ;-)

**Comment by FlyingDiver** [comment]
Yeah, OK,  maybe not.

**Comment by FlyingDiver** [comment]
> if you need access to the unit, let me know I can setup an account for you.

Yeah, maybe that would be best.  Send me the info in a PM on the Indigo forums.

**Comment by FlyingDiver** [comment]
@Koreysherwin - Can you download the most recent commit and try it?  I did a minor tweak to the UDMP login URL.

**Comment by Koreysherwin** [comment]
Starting plugin "miniUniFi 0.0.5" (pid 81915)
   Started plugin "miniUniFi 0.0.5"
   miniUniFi Error                 UniFi Controller Login Connection Error: HTTPSConnectionPool(host='192.168.0.254', port=8443): Max retries exceeded with url: /api/auth/login (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x110057650>: Failed to establish a new connection: [Errno 61] Connection refused',))

**Comment by FlyingDiver** [comment]
Yeah, it's not the URL.  It's the HTTPS connection isn't happening at all.  Something is blocking the TCP connection to that port.  Does the same thing happen in a terminal window?

`curl -k "https://192.168.0.254:8443/api/auth/login`

**Comment by Koreysherwin** [comment]
its the port.
8443 is not used on the UDMP it seems

**Comment by FlyingDiver** [comment]
What does it use?  80? 8080?

**Comment by Koreysherwin** [comment]
it hits it with 80, or no port specified

**Comment by FlyingDiver** [comment]
That makes sense, 80 is the default for HTTP if not specified.  But 443 is the default for HTTPS.  Try that one.

**Comment by Koreysherwin** [comment]
in terminal?  like this?

curl -k "http://192.168.0.254:443/api/auth/login

**Comment by FlyingDiver** [comment]
Yes.  Did you try 80 in the plugin?

**Comment by Koreysherwin** [comment]
this is 443:

  miniUniFi Error                 UniFi Controller Login Error: 404

This is 80:

   miniUniFi Error                 UniFi Controller Login Connection Error: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:727)

**Comment by Koreysherwin** [comment]
you want access to the machine via iMessage screen sharing?

**Comment by FlyingDiver** [comment]
OK, that all makes sense.  443 is correct for HTTPS, but there's no login info provided so you get that error.

80 is HTTP, and it fails on the HTTPS connection.

Give me a minute.

**Comment by Koreysherwin** [comment]
I see why you use GitHub instead of the Indigo forms, this is handy!

**Comment by FlyingDiver** [comment]
Edit the controller device and put 443 in the port field, then restart.

**Comment by Koreysherwin** [comment]
Oct 25, 2020 at 10:56:02 AM
   Reloading plugin "miniUniFi 0.0.5"
   Stopping plugin "miniUniFi 0.0.5" (pid 87906)
   Stopped plugin "miniUniFi 0.0.5"
   Starting plugin "miniUniFi 0.0.5" (pid 88569)
   Started plugin "miniUniFi 0.0.5"
   miniUniFi Error                 UniFi Controller Login Error: 404

**Comment by Koreysherwin** [comment]
Starting plugin "miniUniFi 0.0.5" (pid 89218)
   Started plugin "miniUniFi 0.0.5"
   miniUniFi                       Starting miniUniFi
   miniUniFi Debug                 updateFrequency = 60.0
   miniUniFi                       UDMP: Starting Device
   miniUniFi Debug                 Starting runConcurrentThread
   miniUniFi Debug                 UDMP: Updating controller
   miniUniFi Debug                 UniFi Controller Test response: 200
   miniUniFi Debug                 UniFi Controller Login response: 404
   miniUniFi Error                 UniFi Controller Login Error: 404
   miniUniFi Debug                 Updating UniFi Clients
   miniUniFi Debug                 Updating UniFi Devices

**Comment by FlyingDiver** [comment]
OK, now we're getting somewhere.  The HTTPs requests are connecting.  404 is "not found", which generally means a bad URL.

**Comment by Koreysherwin** [comment]
https://192.168.0.254/api/auth/login 
in safari, results in:
Method Not Allowed

**Comment by FlyingDiver** [comment]
Yeah, the login is a POST not GET.  And you need the auth credentials in the POST body.

I just pushed another commit to GitHub.  Won't fix the problem, but might give more info to debug.  Please try it.

**Comment by Koreysherwin** [comment]
seems to be the same version ?  

I trashed the old plugin and replaced with this incase it was just versioning issue, but no more info in the debug.

![Screen Shot 2020-10-25 at 11 33 33 AM](https://user-images.githubusercontent.com/51178437/97115785-f3cb2300-16b5-11eb-91ae-3f49beb00114.png)

**Comment by FlyingDiver** [comment]
Yes, I did not bump the version number yet.  Please restart the plugin and show the output.  There should be several more lines of output.

**Comment by Koreysherwin** [comment]
Started plugin "miniUniFi 0.0.5"
   miniUniFi                       Starting miniUniFi
   miniUniFi Debug                 updateFrequency = 60.0
   miniUniFi                       UDMP: Starting Device
   miniUniFi Debug                 Starting runConcurrentThread
   miniUniFi Debug                 UDMP: Updating controller
   miniUniFi Debug                 UniFi Controller Test response: 200
   miniUniFi Debug                 UniFi Controller Login response: 404
   miniUniFi Error                 UniFi Controller Login Error: 404
   miniUniFi Debug                 Updating UniFi Clients
   miniUniFi Debug                 Updating UniFi Devices
   miniUniFi Debug                 UDMP: Updating controller
   miniUniFi Error                 UniFi Controller Get Sites Error: 401
   miniUniFi Debug                 Updating UniFi Clients
   miniUniFi Debug                 Updating UniFi Devices

**Comment by FlyingDiver** [comment]
That is not the latest version.  I'll tag it with a release number.

https://github.com/FlyingDiver/Indigo-miniUniFi/releases/tag/0.0.6

**Comment by Koreysherwin** [comment]
Started plugin "miniUniFi 0.0.6"
   miniUniFi                       Starting miniUniFi
   miniUniFi Debug                 updateFrequency = 60.0
   miniUniFi                       UDMP: Starting Device
   miniUniFi Debug                 Starting runConcurrentThread
   miniUniFi Debug                 UDMP: Updating controller
   miniUniFi Debug                 UniFi Controller Test response: 200
   miniUniFi Error                 UniFi Controller Login Status: 404
   miniUniFi Error                 UniFi Controller Login URL: https://192.168.0.254:443/api/auth/login
   miniUniFi Error                 UniFi Controller Login Headers: {'X-Response-Time': '8ms', 'Content-Length': '9', 'X-XSS-Protection': '1; mode=block', 'X-Download-Options': 'noopen', 'X-Content-Type-Options': 'nosniff', 'Content-Type': 'text/plain; charset=utf-8', 'Accept-Ranges': 'bytes', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Vary': 'Origin', 'Connection': 'keep-alive', 'Date': 'Sun, 25 Oct 2020 20:18:45 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'X-DNS-Prefetch-Control': 'off', 'X-CSRF-Token': 'bc2ef874-ba14-4dd3-adf7-0d41487d4016'}
   miniUniFi Debug                 Updating UniFi Clients
   miniUniFi Debug                 Updating UniFi Devices

**Comment by FlyingDiver** [comment]
https://github.com/FlyingDiver/Indigo-miniUniFi/releases/tag/0.0.7

**Comment by Koreysherwin** [comment]
Loading plugin "miniUniFi 0.0.7"
   Starting plugin "miniUniFi 0.0.7" (pid 27392)
   Started plugin "miniUniFi 0.0.7"
   miniUniFi                       Starting miniUniFi
   miniUniFi Debug                 updateFrequency = 60.0
   miniUniFi                       UDMP: Starting Device
   miniUniFi Debug                 Starting runConcurrentThread
   miniUniFi Debug                 UDMP: Updating controller
   miniUniFi                       UniFi Controller Test Status: 200
   miniUniFi                       UniFi Controller Test URL: https://192.168.0.254:443/
   miniUniFi                       UniFi Controller Test Headers: {'X-Response-Time': '2ms', 'Content-Length': '357', 'X-XSS-Protection': '1; mode=block', 'X-Download-Options': 'noopen', 'X-Content-Type-Options': 'nosniff', 'Content-Type': 'text/html; charset=utf-8', 'Accept-Ranges': 'bytes', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Vary': 'Origin', 'Connection': 'keep-alive', 'Set-Cookie': 'TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjc3JmVG9rZW4iOiIzNDM0ZjkxOC1kMWY4LTRhNWUtOGU4OC04MjY3Y2ZmZTcyOWIiLCJpYXQiOjE2MDM2NjAxNjksImV4cCI6MTYwMzY2Mzc2OX0.zSwEzsdA_Ix3InG8lJKYRg5kdGZVFPy8UUBcPggy6hI; path=/; secure; httponly', 'Date': 'Sun, 25 Oct 2020 21:09:29 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'X-DNS-Prefetch-Control': 'off', 'X-CSRF-Token': '3434f918-d1f8-4a5e-8e88-8267cffe729b'}
   miniUniFi                       UniFi Controller Test Content: 
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><link href="/2.css" rel="stylesheet"></head>
<body>
<div id="root"></div>
<script type="text/javascript" src="/vendor.3ea3704e.chunk.js"></script><script type="text/javascript" src="/main.c0fb843d.js"></script></body>
</html>

   miniUniFi                       UniFi Controller Login Status: 404
   miniUniFi                       UniFi Controller Login URL: https://192.168.0.254:443/api/auth/login
   miniUniFi                       UniFi Controller Login Headers: {'X-Response-Time': '4ms', 'Content-Length': '9', 'X-XSS-Protection': '1; mode=block', 'X-Download-Options': 'noopen', 'X-Content-Type-Options': 'nosniff', 'Content-Type': 'text/plain; charset=utf-8', 'Accept-Ranges': 'bytes', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Vary': 'Origin', 'Connection': 'keep-alive', 'Date': 'Sun, 25 Oct 2020 21:09:29 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'X-DNS-Prefetch-Control': 'off', 'X-CSRF-Token': '3434f918-d1f8-4a5e-8e88-8267cffe729b'}
   miniUniFi                       UniFi Controller Login Content: Not Found
   miniUniFi Debug                 Updating UniFi Clients
   miniUniFi Debug                 Updating UniFi Devices

**Comment by FlyingDiver** [comment]
Sigh.  No content on the 404 reply.  I was hoping for something to help track down the error.

**Comment by FlyingDiver** [comment]
Any chance you could set up a port forward and local account on the UDMP so that I can try to connect to it directly?

**Comment by Koreysherwin** [comment]
Sent email.

**Comment by FlyingDiver** [comment]
Fixed in https://github.com/FlyingDiver/Indigo-miniUniFi/releases/tag/0.0.10
